# Generated by Django 5.0.13 on 2025-12-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шага')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('color', models.CharField(choices=[('primary', 'Синий'), ('danger', 'Красный'), ('warning', 'Желтый'), ('success', 'Зеленый'), ('info', 'Голубой')], default='primary', max_length=20, verbose_name='Цвет')),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.businessprocess')),
            ],
            options={
                'verbose_name': 'Шаг процесса',
                'verbose_name_plural': 'Шаги процесса',
                'ordering': ['order'],
            },
        ),
    ]
